name: Build & Publish

on:
  push:
    branches:
      - master
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Composer Dependencies
      run: composer install --no-ansi --no-interaction --ignore-platform-reqs --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate env files
      run: |
        cp .env.example .env
        php artisan key:generate
        touch database/database.sqlite
    - name: Run PhpCsFixer
      run: ./vendor/bin/php-cs-fixer fix --dry-run
    - name: phpunit tests
      run: php artisan test
